-- ADD FABRICANTE
INSERT INTO FABRICANTE(ID, NOME) VALUES(1, 'BAUDUCCO');
INSERT INTO FABRICANTE(ID, NOME) VALUES(2, 'NESTLE');

-- ADD PRODUTO
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(1, 'TORRADA', '100', 'GRAMAS', 1);
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(2, 'TORRADA', '100', 'GRAMAS', 2);

-- ADD ESTABELECIMENTO
INSERT INTO ESTABELECIMENTO(ID, NOME, NUMERO_CNPJ, ENDERECO)
VALUES(1, 'SUPERMERCADOS ZONA SUL', '01222233233333', 'RUA MACHADO DE ASSIS, RJ, FLAMENGO');