-- ADD FABRICANTE
INSERT INTO FABRICANTE(ID, NOME) VALUES(1, 'BAUDUCCO');
INSERT INTO FABRICANTE(ID, NOME) VALUES(2, 'NESTLE');

-- ADD PRODUTO
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(1, 'TORRADA', '100', 'GRAMAS', 1);
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(2, 'TORRADA', '100', 'GRAMAS', 2);
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(3, 'CHOCOLATE', '100', 'GRAMAS', 2);

-- ADD ESTABELECIMENTO
INSERT INTO ESTABELECIMENTO(ID, NOME, NUMERO_CNPJ, ENDERECO)
VALUES(1, 'SUPERMERCADOS ZONA SUL', '01222233233333', 'RUA MACHADO DE ASSIS, RJ, FLAMENGO');

-- ADD COMPRA
INSERT INTO COMPRA(ID, ESTABELECIMENTO_ID, DATA_COMPRA, VALOR_TOTAL)
VALUES(1, 1, '2024-07-06', '100.33');

INSERT INTO COMPRA_PRODUTO(ID, PRODUTO_ID, VALOR, QUANTIDADE) VALUES(1, 2, 7.33, 5);
INSERT INTO COMPRA_PRODUTO(ID, PRODUTO_ID, VALOR, QUANTIDADE) VALUES(2, 3, 10.14, 1);

INSERT INTO COMPRA_ITEM_COMPRA(ITEM_COMPRA_ID, COMPRA_ID) VALUES(1, 1);
INSERT INTO COMPRA_ITEM_COMPRA(ITEM_COMPRA_ID, COMPRA_ID) VALUES(2, 1);