-- ADD FABRICANTE
INSERT INTO FABRICANTE(ID, NOME) VALUES(1, 'BAUDUCCO');
INSERT INTO FABRICANTE(ID, NOME) VALUES(2, 'NESTLE');

-- ADD PRODUTO
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(1, 'TORRADA', '100', 'GRAMAS', 1);
INSERT INTO PRODUTO(ID, NOME, PESO, MEDIDA, FABRICANTE_ID) VALUES(2, 'TORRADA', '100', 'GRAMAS', 2);